### ISSUE TITLE
Get with limit with deleted data can return empty List

### ISSUE THREAD

**Issue by mmimeault** [wajam/mry#146]
Doing a get with a limit can return an empty list (results) even if there is still data.

Example:
- Model: City with Streets. 
- Data: City 'Montreal' has 26 streets. (from 'A' to 'Z')
1. Doing a get with limit(1) on city/id('Montreal')/streets give you street 'A'.
2. Delete city/id('Montreal')/streets/id('A')
3. Doing a get with limit(1) on city/id('Montreal')/streets give you an empty street list instead of street 'B'.

**Comment by alexbergeron** [comment]
Fixed by #155 (There is also a long-term fix if performance starts to take a hit, but this has yet to happen, so I'm closing the issue now)
